workflows:
  ios-workflow:
    name: Flutter App
    labels:
      - QA
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - ngocthien16@gmail.com
      scripts:
        - echo 'Post-publish script'